name: React CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # Node 버전 세팅
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 원하는 Node 버전(예: 18, 16 등)

      # Yarn 설치 & 의존성 설치
      - name: Install dependencies
        run: yarn install

      # (선택) Yarn 캐시
      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       node_modules
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # 빌드
      - name: Build
        run: yarn build

      # 테스트
      - name: Test
        run: yarn test --watch=false
